# theme: jekyll-theme-cayman  # Disabled to use custom theme
title: "Lập trình Python cơ bản"
description: "Sách học Python dành cho người mới bắt đầu - Miễn phí và Open Source"

# GitHub repository
repository: taipm/python_book
baseurl: /python_book
url: https://taipm.github.io

# Author info
author:
  name: Tai PM
  email: taipm@example.com
  url: https://github.com/taipm

# Navigation
navbar:
  - title: "Trang chủ"
    url: /
  - title: "Chương"
    url: /chapters/
  - title: "Dự án"
    url: /projects/
  - title: "Code Examples"
    url: /code-examples/
  - title: "GitHub"
    url: https://github.com/taipm/python_book

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Markdown settings
markdown: kramdown
highlighter: rouge

# Syntax highlighting  
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    block:
      line_numbers: false

# SEO settings
lang: vi-VN
timezone: Asia/Ho_Chi_Minh
social:
  name: Tai PM
  links:
    - https://github.com/taipm

# Google Analytics (optional)
# google_analytics: UA-XXXXXXXXX-X

# Exclude from processing
exclude:
  - README.md
  - LICENSE
  - Gemfile
  - Gemfile.lock
  - node_modules
  - package.json
  - package-lock.json
  - .gitignore
  - .env
  - .env.example
  - CNAME.example
  - vendor/
  - scripts/
  - .vscode/
  - .github/

# Include
include:
  - _pages

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: "chapters"
      type: "pages"
    values:
      layout: "chapter"
  - scope:
      path: "projects"
      type: "pages"
    values:
      layout: "project"

# GitHub Pages settings
github: [metadata]
safe: true
incremental: false
